name: mingw64 build env on archlinux
description: mingw64 build env on archlinux
author: Sebastian Reimers <hallo@studio-link.de>

inputs:
  run:
    required: true

runs:
    using: docker
    image: docker://ghcr.io/sreimers/archlinux-mingw:1.0
    env:
        BUILD_CMD: ${{ inputs.run }}
