name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: sreimers/action-archlinux-mingw@main
      with:
        run: "/usr/bin/i686-w64-mingw32-cc --version"